### ISSUE TITLE
mc to discord error

### ISSUE THREAD

**Issue by iceyman** [k8thekat/GatekeeperV2#101]
# Information [REQUIRED]

### **Which Server Type?**
The drop down value when making the instance *eg. Minecraft or VRising*
Minecraft

### **Which Platform?** 
*eg. AMP, Linux, Windows*
Linux AMP

### **Describe the bug**

say something in MC and didn't display in discord but discore can chat to MC 

6/17/2024 08:30:39 AM [Gatekeeper] [ERROR] Unhandled exception in internal background task 'ampserverconsole_chat_messages_send'.
Traceback (most recent call last):
File "/AMP/gatekeeperv2/venv/lib/python3.11/site-packages/discord/ext/tasks/__init.py", line 239, in _loop
await self.coro(*args, **kwargs)
File "/AMP/gatekeeperv2/GatekeeperV2-main/cogs/AMP_tasks_cog.py", line 318, in amp_server_console_chat_messages_send
Server.Chat_Message(message=message_contents, author_prefix=author_prefix, author=author, server_prefix=AMPServer_Chat.Discord_Chat_Prefix)
TypeError: AMPInstance.Chat_Message() got an unexpected keyword argument 'server_prefix'

---
# Additional Information [NOT REQUIRED]

### **Screenshots**
![Screenshot_18](https://github.com/k8thekat/GatekeeperV2/assets/5343324/1c889a15-6ad5-4095-89a9-7f52daf76008)

**Comment by k8thekat** [comment]
This should be fixed.

Thanks for the report.
