### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by iceyman** [k8thekat/GatekeeperV2#102]
# Information [REQUIRED]

### **Which Server Type?**
The drop down value when making the instance *eg. Minecraft or VRising*

gatekeeper

### **Which Platform?** 
*eg. AMP, Linux, Windows*
Linux ubuntu

### **Describe the bug**

updated gatekeeper and got an error after startup

---
# Additional Information [NOT REQUIRED]

### **To Reproduce**
i updated from older version 

### **Screenshots**
![Screenshot_28](https://github.com/user-attachments/assets/b99e76f5-8a69-4b4e-aab0-3fb3f94fbd47)

**Comment by k8thekat** [comment]
Currently have a hotfix branch up; I do need to test it locally before I push to main. 

You are welcome to download the files manually and overwrite. Just do not hit "Update" on the AMPInstance or it will pull the older version.

Thanks.

**Comment by iceyman** [comment]
Thanks for fixing , i stopped bot and uploaded the files you changed and now i get this error 
![Screenshot_32](https://github.com/user-attachments/assets/e435cd67-b82c-4adf-891e-f82fdc03db5f)

**Comment by k8thekat** [comment]
Hey, I just fixed the circular import issue. 

https://github.com/k8thekat/GatekeeperV2/tree/102-error-after-update

**Comment by iceyman** [comment]
Working now thanks
