### ISSUE TITLE
Feature request: Donator discord role. 

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#13]
Would be fantastic to be able to automatically add the donator role ID to users with a specific Discord role.
Just like how staff interactions with the bot are filtered via discord role, but for donators requesting whitelisting on specific donator only servers. 

That would be a tremendous addition when you have time! 
Thanks!

**Comment by k8thekat** [comment]
Hey! This was added in my most recent commit to `devtesting` See [75a7bf9ec](https://github.com/k8thekat/GatekeeperV2/commit/75a7bf9eca125ac1e3606be01a926f6c4e489109)

Thanks for the suggestion!
