### ISSUE TITLE
Feature request: Customised chat prefixes based on server source or user role.

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#14]
Just a thought, would be great to be able to add a prefix to the discord output based on the source server.
So instead of discord showing 
{username}: (chat message)

it shows:
{prefix}{username}:(chat message)

The reason for this is it can help identify in discord what server a message came from when multiple servers output to the same channel. 

eg. a command /server prefix (ServerName) (prefix)
then appends that prefix to any message being forwarded to discord from that server.

Not sure how hard this would be or if it is scope but might be worth adding!

Bonus points but probably way out of scope, you could also consider adding a secondary prefix setting for staff (those with the Discord role matching what is used in /bot setup) and donator roles (those who have /user add (name) donator = true).

eg. {CustomServerPrefix}(CustomRolePrefix){username}:(chat message)

This would mostly be so staff can have say [Mod] appended to their messages showing in discord from Minecraft, or could be for donators to have [Supporter] added.

example commands:

/bot prefix (staff/donor) (Prefix)

Thanks again!

**Comment by k8thekat** [comment]
I like this idea, I plan to pair it hand in hand with my new permissions setup. You'll be able to set a permission role via a file and ill add a table entry for prefix; which will allow for customization of per role prefix.

Ill see about handling the server prefix from cross server messages. May take me a bit longer.

**Comment by k8thekat** [comment]
This was added in Beta-3.0.0 Update. Servers now have unique prefix's and users can have a prefix via bot_perms.json config.
