### ISSUE TITLE
Discord Support Tickets

### ISSUE THREAD

**Issue by blacksythe** [k8thekat/GatekeeperV2#15]
Would be a nice addition to the bot to be able to add a support category that the bot looks after.

1 Master channel where users run a command like /support ticket

Bot then creates either a new channel or a thread with perms set for the user to access this channel/thread

User can then add their issue to the ticket.

user should be able to close their own ticket as well

staff should also close tickets down if needed
mb an option to automatically @staff if no one has posted in the ticket for a period of time.

**Comment by k8thekat** [comment]
There is many other bots that can do this. I do not plan to implement this.
