### ISSUE TITLE
More control over who can run a command.

### ISSUE THREAD

**Issue by blacksythe** [k8thekat/GatekeeperV2#16]
With current bot configuration I see 3 ways of doing this.

A. With current configuration

Add additional configuration file to define which commands are admin only
For example

bot stop = admin
bot restart = admin
server restart = staff

B. With additional roles

bot stop = admin
bot restart = dev
server restart = staff

C. Customization Extravaganza 

`admin {
roleid = ""
permissions: "all"
}

dev {
roleid = ""
permissions: "all_bot_commands", "all_server_commands"
}

maintenance {
roleid = ""
permissions: "all_server_commands", "bot restart", "bot start"

moderator {
roleid = ""
permissions: "server kick {user}", "server ban {user} {time (0 for perm)}

general
roleid = "(set this to 0 for everyone, otherwise deny everything)"
permissions: "server info", "spark tps", "other custom commands to be defined that can be sent to the server"
`

**Comment by k8thekat** [comment]
This was added in [56c5603](https://github.com/k8thekat/GatekeeperV2/commit/56c5603507770c56f46a7b25653225ec2dec4f0b).

Will be testing stability and permissions shortly.
