### ISSUE TITLE
factorio module not detected

### ISSUE THREAD

**Issue by blacksythe** [k8thekat/GatekeeperV2#17]
Amp api?

Bot appears to ignore factorio, might be the case for other custom modules, untested

**Comment by k8thekat** [comment]
I don't currently have a dedicated module for Factorio at this time. 

Currently it should default to the Generic Module and still allow you to interact with the server with basic commands.

If you are getting errors or the server is not showing up in any form(eg. /server status server_name), please provide me with the error messages and comment on this issue.

Thanks,
Kat.

**Comment by k8thekat** [comment]
This has been addressed and I have added support for Factorio. Should be coming in a recent PR.

Enjoy.
