### ISSUE TITLE
Bug: bot creating users, setting permissions and new instances

### ISSUE THREAD

**Issue by blacksythe** [k8thekat/GatekeeperV2#18]
1. If the bot is refreshed and given super admin again, it recreates the user with the same name, ideally, it will check the user exists and amend the existing one.
First image is old user in a new instance
![image](https://user-images.githubusercontent.com/11398873/183135494-67ef6559-9066-4b36-b619-4d66f1370351.png)
Second image is new user in a new instance this was done after updating the bot
![image](https://user-images.githubusercontent.com/11398873/183135613-a40faeff-b4a0-4585-a00f-f9c88149fd52.png)

2. The bot does not set perms in any newly created instances, this may only be achievable if given super admin, but I will leave this in your capable hands

**Comment by k8thekat** [comment]
This will be fixed in the upcoming PR.

Thanks for sharing!
