### ISSUE TITLE
'/bot utils clean' command cleans non-bot messages

### ISSUE THREAD

**Issue by Acheronx98** [k8thekat/GatekeeperV2#51]
When running the command '/bot utils clean' command and filling out the remainder of the fields, it deletes other user's messages and not just the bot despite explicitly stating it only cleans the bot messages.

**Comment by k8thekat** [comment]
Are you setting the `all` flag to `False`?

It defaults to True; so if you don't set it to False it will remove all messages.

I will update the documentation on the command and add a description to the parameter field.

**Comment by k8thekat** [comment]
Added documentation and description of all parameters for `/bot utils clear`

See version 4.4.0+
