### ISSUE TITLE
Staff role ID not updating in /bot settings

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#6]
Latest version, After updating the command for setting staff role works fine.
I have tested the functionality and usage is restricted.
However running /bot settings displays staff role id as none

have restarted bot and same outcome.
minor issue as functionality is there, just a display issue I think.

**Comment by k8thekat** [comment]
This issue was fixed in commit: 154ef3236b79e0511c65cc0ef74d023c6aeabf6e

Thanks for submitting the issue! <3
