### ISSUE TITLE
setting the donater flag to false does not change the banner

### ISSUE THREAD

**Issue by FeminalPanda** [k8thekat/GatekeeperV2#62]
/server settings donator <server> true, sets the true flag successfully but the opposite does not set it back to false.

**Comment by FeminalPanda** [comment]
this command does not exist. looks to be replaced with /server settings donator (server, flag)

- `/server donator (flag)` - Sets Donator Only Flag for the AMP Dedicated server to True
    - **ATTENTION**: This doesn't prevent players without the rank from connecting; only for auto whitelisting purposes.

**Comment by k8thekat** [comment]
This has been fixed in my `devtesting` branch and I have updated the documentation. Thank you!

**Comment by k8thekat** [comment]
Closing Issue as this has been fixed in v4.4.8
-> https://github.com/k8thekat/GatekeeperV2/commit/bc73355e879f4b6df0296e9a109f4e350234fab7
