### ISSUE TITLE
Server Banners Host Color 

### ISSUE THREAD

**Issue by heykiditsaaron** [k8thekat/GatekeeperV2#64]
Changing the custom server banner host font color has no effect.

**Comment by k8thekat** [comment]
This has been fixed in my `devetesting` branch and will be coming to `main` shortly.

**Comment by k8thekat** [comment]
Closing Issue as this has been fixed in v4.4.8
-> https://github.com/k8thekat/GatekeeperV2/commit/bc73355e879f4b6df0296e9a109f4e350234fab7
