### ISSUE TITLE
Individual specific server banners 

### ISSUE THREAD

**Issue by heykiditsaaron** [k8thekat/GatekeeperV2#65]
It would be nice to be able to show specific server banners in discord as opposed to just popping them all up at once.

**Comment by k8thekat** [comment]
This is being looked into; once major issues/bugs have been handled this will be worked on.

**Comment by HunterAP** [comment]
I don't know if my request is the same or not, but my Discord server has a channel for each game server. I'd like to be able to post each game's banner to its own channel.

**Comment by k8thekat** [comment]
This was released in 4.5.0.

Enjoy!
