### ISSUE TITLE
Fully manual whitelisting

### ISSUE THREAD

**Issue by snaggo** [k8thekat/GatekeeperV2#66]
It would be nice to be able to completely remove the whitelist wait-time, or make it infinite, so the whitelist approval can be done fully manual.

**Comment by k8thekat** [comment]
This will be coming out shortly after I finish bug fixes. Thanks for the suggestion.

**Comment by snaggo** [comment]
Maybe as an addition to that - specify roles which are able to auto-whitelist themselves/bypass the wait-time (e.g. for friends/trusted persons)

**Comment by k8thekat** [comment]
I could possibly have it tie to `Donators` for now and expand later.

**Comment by k8thekat** [comment]
Closing Issue as this has been implemented in the current release.
-> https://github.com/k8thekat/GatekeeperV2/commit/bc73355e879f4b6df0296e9a109f4e350234fab7
