### ISSUE TITLE
Feature request: Cross server chat relay.

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#7]
Being able to relay chat across multiple AMP servers would be a really handy feature.
Currently it is possible to output chat to a single discord channel from multiple servers.
Any message sent to that channel is then sent to all AMP (minecraft) servers set to use that channel for chat.

However this does not work the other way in that if someone on Minecraft1 sends a message, it goes to discord, but is not then forwarded to Minecraft2 that also uses that same chat channel.

Given it is the same bot, theoretically (I am not a programmer and only know basics), would it be possible to add a check like:

if server chat relay == true then 
    for server chat output to discord
    also send chat input to AMP servers with relay == true

Thanks!

**Comment by k8thekat** [comment]
Hey! Just wanted to say thank you fro the suggestion! 

Your feature is coming soon!
See [9eb5548cd](https://github.com/k8thekat/GatekeeperV2/commit/9eb5548cd3bf8da8e7f9ac58f7f851d80a8f49a6)
