### ISSUE TITLE
Error Setting Value `/server banner settings` Blur Amount

### ISSUE THREAD

**Issue by IceOfWraith** [k8thekat/GatekeeperV2#74]
This is a benign error, but makes it seem like the bot is not changing the blur amount correctly. I'll provide a debug log through Discord from a time I changed the blur intensity. The value is updated as far as I can tell, and the banner refreshes shortly after, but this error is consistent.

![Screenshot 2023-02-06 210645](https://user-images.githubusercontent.com/96364530/217138086-c5ab0c57-7608-4697-990c-c331445466de.jpg)

**Comment by k8thekat** [comment]
Okay; I will look into this. Thanks <3

**Comment by k8thekat** [comment]
This issue has been fixed in my most recent Hotfix/Merge
-> https://github.com/k8thekat/GatekeeperV2/commit/e344e40e1756cee92abae14a93f6a2b62fc7ba02
