### ISSUE TITLE
Feature Request: Ability to mass edit for banners

### ISSUE THREAD

**Issue by IceOfWraith** [k8thekat/GatekeeperV2#75]
I have roughly 20 servers I am editing banners for. It would be great to be able to set a specific blur/font setting for all banners at once. I'm imagining "All" as a server option when entering the `/server banner settings server:All` to edit across the board versus selecting a specific server. Then the banner editor uses the first from the list as the example banner image.

**Comment by k8thekat** [comment]
This has been released! Enjoy <3
