### ISSUE TITLE
No module named "AMP_Permissions"

### ISSUE THREAD

**Issue by Acheronx98** [k8thekat/GatekeeperV2#78]
Doing some testing I found a bug having to deal with "what happens if Gatekeeper no longer exists?" in AMP so, tl;dr it breaks it, obviously, but it should re-create the role [giving the user Gatekeeper has assigned to it] and assign it all the perms it needs. That's not the case. It looks like a misspelled module is breaking it, I don't know, it's weird.

![image](https://user-images.githubusercontent.com/5783760/217941467-3fbf9cfe-34a2-49eb-b8e3-57c59a99fd3e.png)

**Changing line 244 in AMP.py fixes the issue**
Rename from 'AMP_Permissions' to 'amp_permissions'
![image](https://user-images.githubusercontent.com/5783760/217942135-07e99021-d4a8-4c07-912c-71a82c87e353.png)
![image](https://user-images.githubusercontent.com/5783760/217942390-cd132b7f-d940-4343-b8f7-69f7a985f5c7.png)

**Comment by k8thekat** [comment]
I wonder if somehow during an update your file got renamed to a lowercase version.

My Linter screams at me trying to use the lowercase version. Ill give this some testing.
Thanks.

**Comment by k8thekat** [comment]
Closing this issue as I believe it was an isolated issue.
