### ISSUE TITLE
Read default value for "Host" in Banner from AMP

### ISSUE THREAD

**Issue by cptnuss-ops** [k8thekat/GatekeeperV2#88]
Hi @k8thekat,
I just installed and configured this awesome tool on my AMP instance.
The banner feature in Discord is super helpful for status and information purposes.

Sadly the IP-Address  stated in the "Host" section is some local 192.XXX.X.X.
I figured out, that the host can be manually changed but I think a good addition would be to read the gameserver IP via the AMP-Api.

This would be something I could develop myself, I this is wished please let me know how I can contribute to your project. 
I just cloned the repo locally, but I wasn't sure how to setup the project for local debugging against a remote server.

Thank you again for this awesome tool!

Best regards,
Lukas

**Comment by k8thekat** [comment]
After talking to Mike and many other developers with AMP/CubeCoders. Pulling the IP from the Instance would be of no benefit as docker/containers would point to a 192.168.XXX.XXX type address and you would have to change it. There are cases were the machine/server would be completely public facing but given the amount of people who use Name Servers this feature is going to be shelved indefinitely. 

Thanks.
