### ISSUE TITLE
AMP Docker instance - No such file or directory  error

### ISSUE THREAD

**Issue by veteranmina** [k8thekat/GatekeeperV2#90]
When attempting to install a new instance of GatekeeperV2 in a docker container it errors with below:

/usr/bin/python3: can't open file '/AMP/gatekeeperv2/GatekeeperV2-main/start.py': [Errno 2] No such file or directory

I have attempted to restart the instance but it continues to fail. Via console going to directory .../amp/.ampdata/instaces/DiscordBot01/gatekeeperv2/GatekeeperV2-main/ only file listed is token.py

Is there a missing step for docker instances?

**Comment by k8thekat** [comment]
Please try clicking the "Update" button and then retry.

**Comment by veteranmina** [comment]
ah! I mistook you're mention of update button for the instance and not the console/status page. I have confirmed files are populated. 

Thank you!
