### ISSUE TITLE
[feature-request] Windows Release

### ISSUE THREAD

**Issue by Bluscream** [k8thekat/GatekeeperV2#92]
![](https://i.imgur.com/nJZDFvE.png)

**Comment by k8thekat** [comment]
Are you using docker containers on AMP? I believe it should support Windows with a docker.

**Comment by Bluscream** [comment]
> Are you using docker containers on AMP? I believe it should support Windows with a docker.
> 
> Otherwise; it will use Linux once you have a docker container.

Do i need to install docker manually to use it with my existing AMP installation?

**Comment by Bluscream** [comment]
> Are you using docker containers on AMP? I believe it should support Windows with a docker.
> 
> Otherwise; it will use Linux once you have a docker container.

After trying docker for windows, it seems like it does not work because virtualization cannot be enabled on vservers

**Comment by k8thekat** [comment]
Sorry; my comment was unspecific.

I would recommend running a docker container of Linux for Gatekeeper; if you ask in CubeCoders discord they should be able to assist you in setting up AMP to use dockers.

**Comment by k8thekat** [comment]
Closing as resolved.
