### ISSUE TITLE
Console Channel Issues and Unlink

### ISSUE THREAD

**Issue by Jamie96ITS** [k8thekat/GatekeeperV2#94]
Setting things up and getting tested, I linked a console to a channel but am not receiving anything in Discord. It sends every Discord message to the console, however. While I investigate and troubleshoot the issue, I discover I'm not sure how to disconnect the console from the channel.

These commands show how to link a channel, but how would one un-link the channel?

https://github.com/k8thekat/GatekeeperV2/blob/d6fa3e323f2f59304d6458cf0be85a83d9bc08e1/COMMANDS.md?plain=1#L150-L157

**Comment by k8thekat** [comment]
What server type are you trying to get the console from?


Resetting channels is fixed in version 4.6.3 -- Update and the Channel issue will be resolved.

**Comment by Jamie96ITS** [comment]
Thanks! That seems to have solved that bit. 

I found the other was my own fault. My bot role did not have permission to manage Webhooks, which are needed for this function. It seems this is attempted/errors to console rarely and I missed it before. 

So that aught to do it then, thanks again!
