### ISSUE TITLE
Deprecate distutils module

### ISSUE THREAD

**Issue by ssfdre38** [k8thekat/GatekeeperV2#95]
Running test on Python 3.12.1 with gatekeeper on my dev branch.
distuils module was deprecated on 3.12 and is now recommended to use to migrate to `setuptools`
https://peps.python.org/pep-0632/#migration-advice
tried to find where its setup to change it to test it on my end to see if it will work. 
![AMP - Application Management Panel - Google Chrome 12_17_2023 11_13_57 PM](https://github.com/k8thekat/GatekeeperV2/assets/1365273/15426abe-b10a-44fa-9ed5-beae5a74a70a)

**Comment by k8thekat** [comment]
This is fixed when changing `numpy` and `yarl` to not have version restrictions in `requirements.txt`

Thanks.
