### ISSUE TITLE
/server status (server) error

### ISSUE THREAD

**Issue by aminoginji** [k8thekat/GatekeeperV2#99]
# Information [REQUIRED]

### **Which Server Type?**
Enshrouded, Ark

### **Which Platform?** 
Windows

### **Describe the bug**
I'm using /server status in discord to open the information panel 
When using the button on that panel i get an error in gatekeeper
[Gatekeeper] [ERROR] AMP_API CallAPI ret is 0: status_code 200 

/server stop
/server start
etc all work just having issue with the panel

**Comment by k8thekat** [comment]
Typically this can fire off if the data from the API call is None. 

Given the status code is `200` I think the command went through but possibly a logic check I have failed. Does this happen every time you you click a button from the `/server status` command for those servers specifically? 

Also which version of Gatekeeper? You can see the version during startup or type `/bot utils status`

Thanks~

**Comment by k8thekat** [comment]
Never mind, I found my logic error. This will be fixed shortly.
